# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e1203204baddfddb1ab6b827c0794a66e212f252718d127769bf4960af2b1c1ddb7c8c8468bf669ed4f1489ebb29ce6049c20b3f89f146210c1d2e292d740f

test:
  secret_key_base: 7822177260810d051e700db10991b34298fe5ec994a7d4e32b9197c53503767080f41bf7866ced7709b55e0e2213c49b0ce43d0ff00f132f89f89f39ad0a9ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
